services:
  db:
    image: mongo:7
    container_name: phonebook-db

    environment:
      MONGO_INITDB_ROOT_USERNAME: phonebook
      MONGO_INITDB_ROOT_PASSWORD: RoKo@2024
      MONGO_INITDB_DATABASE: phonebook_db

    ports:
      - "27018:27017"

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u phonebook -p 'RoKo@2024' --eval 'db.adminCommand(\"ping\")'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s


  backend:
    build:
      context: ./backend

    container_name: phonebook-backend

    environment:
      MONGODB_URI: mongodb://phonebook:RoKo%402024@db:27017/phonebook_db?authSource=admin

    depends_on:
      db:
        condition: service_healthy

    restart: on-failure


  frontend:
    build:
      context: ./frontend

    container_name: phonebook-frontend

    ports:
      - "80:80"

    depends_on:
      - backend


  api-tests:
    profiles: ["test"]
    image: maven:3.9-eclipse-temurin-17
    working_dir: /src
    volumes:
      - ./backend:/src
      - maven_cache:/root/.m2
    environment:
      MONGODB_URI: mongodb://phonebook:RoKo%402024@db:27017/phonebook_test?authSource=admin
    depends_on:
      db:
        condition: service_healthy
    command: ["mvn", "test"]


volumes:
  mongo_data:
  maven_cache:
