server.port=8000
spring.application.name=phonebook-api

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/phonebook_db}

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.mapper.accept-case-insensitive-properties=true
spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
